### ISSUE TITLE
Unable to add multiple sections in Admin without saving in between.

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#158]

**Comment by Rikuoja** [comment]
Yields the error "Please correct the duplicate data for id".

**Comment by tuomas777** [comment]
Cannot reproduce, probably was fixed when IDs were changed non-editable

**Comment by Rikuoja** [comment]
Hm, I think this was caused by the generated ID being the same for both added sections. How did non-editable ID cause the generated ID to change between sections?

**Comment by tuomas777** [comment]
I think the error came from form validation (before new IDs were generated) which isn't happening any more as the field is non-editable.

**Comment by Rikuoja** [comment]
Closing as non-reproducible.
