### ISSUE TITLE
As a developer I need API to create, delete and resize images attached to hearing to support UI story #35 #36 #37

### ISSUE THREAD

**Issue by piotras** [City-of-Helsinki/kerrokantasi#18]

**Comment by piotras** [comment]
API should also allow to add captions to image. 

"As an official I want to be able to add caption for images which I have uploaded."
https://github.com/City-of-Helsinki/kerrokantasi-ui/issues/41

**Comment by akx** [comment]
API not required in MVP; admin done via admin

**Comment by Rikuoja** [comment]
Implemented otherwise, thumbnails in issue #243
