### ISSUE TITLE
Allow POSTing image when POSTing comments

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#220]

**Comment by Rikuoja** [comment]
Post image encoded inline. No need to POST to image endpoint separately.

**Comment by Rikuoja** [comment]
Also, we do not want anyone to be able to POST images that are not related to a comment.

**Comment by akx** [comment]
@Rikuoja Maybe define allowed mime types and size limits?

**Comment by Rikuoja** [comment]
Yeah, 1 MB would be a sensible limit as that's the same as our server default. Perhaps it's better to hardcode a limit to django too?

**Comment by Rikuoja** [comment]
Though, at the moment the server would refuse any comment over 1 MB if the geometry and image together are over the limit, even if the image is smaller.

**Comment by Rikuoja** [comment]
As for mime types, I would allow any that django imagefield (i.e. Pillow) accepts and common browsers can render, unless you have a stricter suggestion?

**Comment by Rikuoja** [comment]
Currently, the use case is mostly images taken directly on mobile.

**Comment by stephawe** [comment]
Should it allow to POST several images ?

**Comment by Rikuoja** [comment]
Hm, indeed the array does allow for several images. I see no reason to limit POSTing to one image, as long as the total size of the message doesn't exceed 1MB?

**Comment by stephawe** [comment]
Me neither. Just wanted to confirm.

**Comment by Rikuoja** [comment]
Yeah, let's allow several images. If the user tries to POST too large images, it's their problem. =)
