### ISSUE TITLE
Allow specifying geometry when POSTing comments

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#223]

**Comment by Rikuoja** [comment]
Any valid Geojson will be accepted as such. Similar to Hearing Geojson field.

**Comment by akx** [comment]
@Rikuoja Maybe this oughta be limited to "a single `Point` or `Polygon`"? (Maybe `LineString` too if you see an use for it.)

In any case, what I'm getting at is that I don't think FeatureCollections, etc. should be allowed.

**Comment by Rikuoja** [comment]
@akx The problem is, a comment may refer to FeatureCollections and should be able to contain them.

In addition to user drawing their own geometry, the comment may refer to an existing geometry object which may be of any type. Obviously, in such case we could only store the URI of the geometry object and not store the geometry, but we want to be able to do filtering etc. based on the geometry.

Therefore, we want the actual geometry to be stored within the comment, even if the geometry is not drawn by user as such.

**Comment by akx** [comment]
Alright :) Thanks for the clarification.

**Comment by Rikuoja** [comment]
Btw this is also why the Geojson should be able to contain extra properties such as fid or URI for the geometry :)
