### ISSUE TITLE
Endpoints do not return all items when JWT token is included in GET

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#253]
When JWT token from a user who has admin rights to an organization is included in GET header, the endpoints no longer behave correctly.

E.g. https://api.hel.fi/kerrokantasi-test/v1/comment/?section=SdKdlbExQiO6nHRScFCcdw6KnOaQxr89&include=plugin_data&limit=10&ordering=-n_votes will return 61 comments if asked without a token, and 0 if asked with a token that has admin rights in an organization.

https://api.hel.fi/kerrokantasi-test/v1/hearing/?limit=99998&ordering=-created_at&include=geojson will return 30 hearings without a token, and 1 if asked with a token. The returned hearing is the only one created by the organization the token has admin rights to.

**Comment by akx** [comment]
The culprit seems to be this code. https://github.com/City-of-Helsinki/kerrokantasi/blob/3b9e882f934f9c56c842075cfc62023a2586fa5c/democracy/views/utils.py#L115-L119

**Comment by Rikuoja** [comment]
I thought so too... but why is also the hearing section comment endpoint underneath it affected? Does it return an empty json if the hearing isn't found?
