### ISSUE TITLE
Transition geojson to proper PostGIS

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#255]
This will allow bbox-filtering of hearings and comments

**Comment by akx** [comment]
It would be good idea to still store the GeoJSON and "cache" it as a `GEOGRAPHY` field for lookups,  as the GeoJSON is required in the frontend anyway.

**Comment by Rikuoja** [comment]
And when it's done, actually implement bbox filtering of hearings and comments, for future use :)
