### ISSUE TITLE
Fix django-admin for contact persons

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#265]
Currently, contact persons cannot be edited in the admin due to server error (HTTP 500).

**Comment by sanesane** [comment]
Other democracy app models are not eorking in admin panel:

- label: can't open admin  list view nor detail view
- SectionType: can't open detail view 
![screenshot from 2017-11-15 14 08 16](https://user-images.githubusercontent.com/12063415/32835786-1bac2f5e-ca10-11e7-8bb0-199a67974449.png)
![screenshot from 2017-11-15 14 08 27](https://user-images.githubusercontent.com/12063415/32835787-1bca57d6-ca10-11e7-8bb5-17f4ded3f924.png)
![screenshot from 2017-11-15 14 11 25](https://user-images.githubusercontent.com/12063415/32835788-1be56d82-ca10-11e7-958a-0c2734906dd3.png)
