### ISSUE TITLE
Add upload endpoint v1/file to allow file uploads linked to a section

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#266]
- [x] Also, add `files` array to the section json (similar to the `images` array) that will list files belonging to a section.

- [ ] For listing the `/v1/file` endpoint, refactor/generalize the https://github.com/City-of-Helsinki/kerrokantasi/blob/master/democracy/views/section.py#L182 `ImageViewSet` so that the same code is used for both `/v1/file` and `/v1/image` endpoints.

- [x] Similarly, add tests for file endpoint and section file listing (similar to existing tests for images) to ascertain that only files belonging to *published* sections are listed.

- [x] Files do exist on the server `media` directory already, uploaded via django-admin, but not exposed at any endpoint. The server should only allow fetching the file if it the hearing is public and the file is listed on the file endpoint; we should use e.g. https://github.com/johnsensible/django-sendfile for that.

- [x] Make a migration to scan existing hearing section HTML for references to existing uploaded files and add them to the database accordingly.

**Comment by Rikuoja** [comment]
Files do exist on the server already, uploaded via django-admin, but not exposed at any endpoint. The server should only allow fetching the file if it the hearing is public and the file is listed on the file endpoint; we should use e.g. https://github.com/johnsensible/django-sendfile for that.

Make a migration to scan existing hearing section HTML for references to existing uploaded files and add them to the database accordingly.

**Comment by sanesane** [comment]
Images are posted as JSON (base64 encoded strings) to API. Do we wan't to use this same approach with files, or FormParser/FileUplodParser instead? [http://www.django-rest-framework.org/api-guide/parsers/#formparser](url)

**Comment by Rikuoja** [comment]
Hm. The GET endpoint must definitely be JSON, as it will have metadata such as the file URL, created date, modified date, organization etc.

Probably the POST and PUT endpoints would not need any metadata along with the file (accepting just the file itself), so we might want to just use a FileUploadParser. However, then the stuff we GET will be totally different from the stuff we POST, but perhaps we can live with that?

**Comment by akx** [comment]
FileUploadParser can't deal with nested/structured data like JSON though, I suppose?

**Comment by sanesane** [comment]
Maybe it's best to use FormParser and MultipartParser in v1/file endpoint to parse POST/PUT request, which should then be form data and allows all necessary metadata to be posted as well. . Is it necessary to implement file upload as inline in Section or Hearing POST?

**Comment by Rikuoja** [comment]
Inline posting should not be allowed, as the files can get very large.

**Comment by jussih** [comment]
POSTing a new file as Multipart form requires that the translated `title` and `caption` values are posted as json-encoded strings. Here's a curl example:

```curl -X POST \
  http://localhost:8000/v1/file/ \
  -H 'accept: application/json' \
  -H 'authorization: JWT [valid jwt token]' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F uploaded_file=@mona_lisa.png \
  -F section=nREpeKghqsGMFGpV5hVaVTVjgviu0lAb \
  -F 'title={"en": "File title", "fi": "Tiedoston otsikko"}' \
  -F 'caption={"en": "File caption", "fi": "Tiedoston kuvaus"}'```
