### ISSUE TITLE
Add default alphabetical ordering to the Label endpoint

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#267]
Ordering by id is not useful for the user :)

**Comment by sanesane** [comment]
UI assumes that API returns only one locale in labels, thus selecting always first item in returned dict. First item can be any locale and this causes UI to show labels in wrong locale. Also changing language in UI do not update labels (see attached screenshot).

Suggestion: UI should select correct locale from returned label data. Labels should be refreshed when language is changed. UI could also sort labels alphabetically at after it has picked correct locale, thus localization/sorting is not necessary in API.

![screenshot from 2017-12-12 11 38 13](https://user-images.githubusercontent.com/12063415/33877460-17edd922-df31-11e7-8799-ecd1fb1bf166.png)

**Comment by Rikuoja** [comment]
That's true. Delegating this to frontend issue https://github.com/City-of-Helsinki/kerrokantasi-ui/issues/429 and its possible continuation, as it seems the frontend has problems with label languages.
