### ISSUE TITLE
Add default alphabetical ordering to Contact person endpoint

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/kerrokantasi#275]
Similar to #267 , returned contact persons should be ordered by last name.

**Comment by sanesane** [comment]
Contact person has only field "name", which contains first name and last name as a single string. This should be refactored to two separate fields "first_name" and "last_name" and needed changes made to API and UI. New issue should be created for this.

**Comment by Rikuoja** [comment]
Hm. I'm actually considering ordering by first name should be sufficient at the moment. I don't know if there is a use case for separating the name into two fields.

Also, we could create a custom ordering filter that actually orders the strings according to the last part of the split string. Wouldn't that be, ehm, interesting?

**Comment by Rikuoja** [comment]
Of course, said filter would be rather heavy on the db side if the contact person list grows, so perhaps better not.

**Comment by Rikuoja** [comment]
Of course, we could just deconstruct the API string into two separate fields, validating it when it comes in.

**Comment by Rikuoja** [comment]
Because I kinda like the simplicity of the `name` field in the API and UI.

**Comment by akx** [comment]
When/if deciding to split things into several fields, remember that KK is supposed to be reusable software, then remember http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ and then despair :D

**Comment by Rikuoja** [comment]
@akx that's what i was thinking exactly :)

**Comment by Rikuoja** [comment]
I believe the only limitation to a name is that it should be a unicode string, unless we get any artists formerly known as Prince.

**Comment by akx** [comment]
Anyway, you can probably do sorting in the UI. Even better, it'd probably be better to have an autocomplete-like box in the UI to allow for filtering, so ordering doesn't really matter at all?

**Comment by Rikuoja** [comment]
@akx there is an autocomplete box, the results just are displayed randomly. First name basis should be sufficient to make it look less of a mess?

**Comment by Rikuoja** [comment]
Of course we'll have to take the assumption #40 (people have names), but any other item on the list should be supported and you can just input whatever string you want.

**Comment by Rikuoja** [comment]
Obviously, ordering random unicode characters is a bit less well defined, but let's stick to the alphabetical ordering in case we have alphabets in the string.

**Comment by akx** [comment]
Probably, yeah. Or just a lazy effort to sort by last name (or rather, sort by reverse name-fragment order) like

```javascript
_.sortBy((contact) => ' '.join(contact.name.split(/\s+/).reverse())
```

which will inevitably break eventually :D

**Comment by Rikuoja** [comment]
Oh yes it will break. But not for all cases, because we are dealing with an autocomplete filter already before returning the list!

**Comment by Rikuoja** [comment]
But yeah, we have people with all manner of compound names and names from different cultures working at the City of Helsinki alone. Not to mention that this software should be globally generic.

**Comment by sanesane** [comment]
So adding ordering to ContactPerson model Meta class should suffice for now? Like so:
```
     class Meta:
         verbose_name = _('contact person')
         verbose_name_plural = _('contact persons')
+        ordering = ['name']
```

**Comment by Rikuoja** [comment]
I believe it should :)
