### ISSUE TITLE
As a developer I need an API to manage user's feedback (comments) about service itself to support UI story #76

### ISSUE THREAD

**Issue by piotras** [City-of-Helsinki/kerrokantasi#35]

**Comment by akx** [comment]
This sounds like it should be done with some external service like Uservoice instead?

**Comment by rambo** [comment]
I think the city has some service selected for this already, @juyrjola can you confirm ?

**Comment by akx** [comment]
(Sorry, misclicked there, @itimo)

Closing -- using uservoice, see https://github.com/City-of-Helsinki/kerrokantasi-ui/issues/76
